type RideStatus =
  | "REQUESTED" | "SEARCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING"
  | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED"
  | "PAYMENT_PENDING" | "PAYMENT_PROCESSING" | "PAYMENT_SUCCESS" | "PAYMENT_FAILED";

export const RIDE_TRANSITIONS: Record<RideStatus, RideStatus[]> = {
  REQUESTED: ["SEARCHING", "CANCELLED"],
  SEARCHING: ["DRIVER_ASSIGNED", "CANCELLED"],
  DRIVER_ASSIGNED: ["DRIVER_ARRIVING", "CANCELLED"],
  DRIVER_ARRIVING: ["DRIVER_ARRIVED", "CANCELLED"],
  DRIVER_ARRIVED: ["IN_PROGRESS", "CANCELLED"],
  IN_PROGRESS: ["COMPLETED"],
  COMPLETED: ["PAYMENT_PENDING"],
  PAYMENT_PENDING: ["PAYMENT_PROCESSING"],
  PAYMENT_PROCESSING: ["PAYMENT_SUCCESS", "PAYMENT_FAILED"],
  PAYMENT_SUCCESS: [],
  PAYMENT_FAILED: [],
  CANCELLED: [],
};

export function canTransition(from: RideStatus, to: RideStatus): boolean {
  return RIDE_TRANSITIONS[from]?.includes(to) ?? false;
}